SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
-- -----
INSERT INTO `lc_countries` (`id`, `status`, `name`, `domestic_name`, `iso_code_1`, `iso_code_2`, `iso_code_3`, `tax_id_format`, `address_format`, `postcode_format`, `postcode_required`, `language_code`, `currency_code`, `phone_code`) VALUES
(1, 1, 'Afghanistan', '', '004', 'AF', 'AFG', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fa', 'AFN', '93'),
(2, 1, 'Albania', '', '008', 'AL', 'ALB', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'sq', 'ALL', '355'),
(3, 1, 'Algeria', '', '012', 'DZ', 'DZA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'ar', 'DZD', '213'),
(4, 1, 'American Samoa', '', '016', 'AS', 'ASM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '96799', 0, 'en', 'USD', '168'),
(5, 1, 'Andorra', '', '020', 'AD', 'AND', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 'AD[0-9]{3}', 0, 'ca', 'EUR', '376'),
(6, 1, 'Angola', '', '024', 'AO', 'AGO', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'pt', 'AOA', '244'),
(7, 1, 'Anguilla', '', '660', 'AI', 'AIA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'XCD', '126'),
(8, 1, 'Antarctica', '', '010', 'AQ', 'ATA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, '', 'XCD', '672'),
(9, 1, 'Antigua and Barbuda', '', '028', 'AG', 'ATG', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'XCD', '126'),
(10, 1, 'Argentina', '', '032', 'AR', 'ARG', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '([A-HJ-NP-Z])?[0-9]{4}([A-Z]{3})?', 0, 'es', 'ARS', '54'),
(11, 1, 'Armenia', '', '051', 'AM', 'ARM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '(37)?[0-9]{4}', 0, 'hy', 'AMD', '374'),
(12, 1, 'Aruba', '', '533', 'AW', 'ABW', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'nl', 'AWG', '297'),
(13, 1, 'Australia', '', '036', 'AU', 'AUS', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'en', 'AUD', '61'),
(14, 1, 'Austria', '', '040', 'AT', 'AUT', '^(AT)?U[0-9]{8}$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'de', 'EUR', '43'),
(15, 1, 'Azerbaijan', '', '031', 'AZ', 'AZE', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'az', 'AZN', '994'),
(16, 1, 'Bahamas', '', '044', 'BS', 'BHS', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'BSD', '124'),
(17, 1, 'Bahrain', '', '048', 'BH', 'BHR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '((1[0-2]|[2-9])[0-9]{2})?', 0, 'ar', 'BHD', '973'),
(18, 1, 'Bangladesh', '', '050', 'BD', 'BGD', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'bn', 'BDT', '880'),
(19, 1, 'Barbados', '', '052', 'BB', 'BRB', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '(BB[0-9]{5})?', 0, 'en', 'BBD', '124'),
(20, 1, 'Belarus', '', '112', 'BY', 'BLR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{6}', 0, 'be', 'BYR', '375'),
(21, 1, 'Belgium', '', '056', 'BE', 'BEL', '^(BE)?0[0-9]{9}$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'nl', 'EUR', '32'),
(22, 1, 'Belize', '', '084', 'BZ', 'BLZ', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'BZD', '501'),
(23, 1, 'Benin', '', '204', 'BJ', 'BEN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fr', 'XOF', '229'),
(24, 1, 'Bermuda', '', '060', 'BM', 'BMU', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[A-Z]{2}[ ]?[A-Z0-9]{2}', 0, 'en', 'BMD', '144'),
(25, 1, 'Bhutan', '', '064', 'BT', 'BTN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'dz', 'BTN', '975'),
(26, 1, 'Bolivia', '', '068', 'BO', 'BOL', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'es', 'BOB', '591'),
(27, 1, 'Bosnia and Herzegowina', '', '070', 'BA', 'BIH', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'bs', 'BAM', '387'),
(28, 1, 'Botswana', '', '072', 'BW', 'BWA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'BWP', '267'),
(29, 1, 'Bouvet Island', '', '074', 'BV', 'BVT', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, '', 'NOK', '47'),
(30, 1, 'Brazil', '', '076', 'BR', 'BRA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}[\\-]?[0-9]{3}', 0, 'pt', 'BRL', '55'),
(31, 1, 'British Indian Ocean Territory', '', '086', 'IO', 'IOT', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 'BBND 1ZZ', 0, 'en', 'USD', '246'),
(32, 1, 'Brunei Darussalam', '', '096', 'BN', 'BRN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[A-Z]{2}[ ]?[0-9]{4}', 0, 'ms', 'BND', '673'),
(33, 1, 'Bulgaria', '', '100', 'BG', 'BGR', '^(BG)?[0-9]{9,10}$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'bg', 'BGN', '359'),
(34, 1, 'Burkina Faso', '', '854', 'BF', 'BFA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fr', 'XOF', '226'),
(35, 1, 'Burundi', '', '108', 'BI', 'BDI', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fr', 'BIF', '257'),
(36, 1, 'Cambodia', '', '116', 'KH', 'KHM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'km', 'KHR', '855'),
(37, 1, 'Cameroon', '', '120', 'CM', 'CMR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'XAF', '237'),
(38, 1, 'Canada', '', '124', 'CA', 'CAN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[ABCEGHJKLMNPRSTVXY][0-9][ABCEGHJ-NPRSTV-Z][ ]?[0-9][ABCEGHJ-NPRSTV-Z][0-9]', 0, 'en', 'CAD', '1'),
(39, 1, 'Cape Verde', '', '132', 'CV', 'CPV', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'pt', 'CVE', '238'),
(40, 1, 'Cayman Islands', '', '136', 'KY', 'CYM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'KYD', '134'),
(41, 1, 'Central African Republic', '', '140', 'CF', 'CAF', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fr', 'XAF', '236'),
(42, 1, 'Chad', '', '148', 'TD', 'TCD', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fr', 'XAF', '235'),
(43, 1, 'Chile', '', '152', 'CL', 'CHL', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'es', 'CLP', '56'),
(44, 1, 'China', '', '156', 'CN', 'CHN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{6}', 0, 'zh', 'CNY', '86'),
(45, 1, 'Christmas Island', '', '162', 'CX', 'CXR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '6798', 0, 'en', 'AUD', '61'),
(46, 1, 'Cocos (Keeling) Islands', '', '166', 'CC', 'CCK', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '6799', 0, 'ms', 'AUD', '61'),
(47, 1, 'Colombia', '', '170', 'CO', 'COL', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'es', 'COP', '57'),
(48, 1, 'Comoros', '', '174', 'KM', 'COM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'ar', 'KMF', '269'),
(49, 1, 'Congo', '', '178', 'CG', 'COG', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fr', 'XAF', '242'),
(50, 1, 'Cook Islands', '', '184', 'CK', 'COK', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'en', 'NZD', '682'),
(51, 1, 'Costa Rica', '', '188', 'CR', 'CRI', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4,5}|[0-9]{3}-[0-9]{4}', 0, 'es', 'CRC', '506'),
(52, 1, 'Cote D\'Ivoire', '', '384', 'CI', 'CIV', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fr', 'XOF', '225'),
(53, 1, 'Croatia', '', '191', 'HR', 'HRV', '^(HR)?[0-9]{11}$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'hr', 'HRK', '385'),
(54, 1, 'Cuba', '', '192', 'CU', 'CUB', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'es', 'CUP', '53'),
(55, 1, 'Cyprus', '', '196', 'CY', 'CYP', '^(CY)?[0-9]{8}L$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'el', 'EUR', '357'),
(56, 1, 'Czech Republic', '', '203', 'CZ', 'CZE', '^(CZ)?[0-9]{8,10}$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{3}[ ]?[0-9]{2}', 0, 'cs', 'CZK', '420'),
(57, 1, 'Denmark', '', '208', 'DK', 'DNK', '^(DK)?[0-9]{8}$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'da', 'DKK', '45'),
(58, 1, 'Djibouti', '', '262', 'DJ', 'DJI', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fr', 'DJF', '253'),
(59, 1, 'Dominica', '', '212', 'DM', 'DMA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'XCD', '176'),
(60, 1, 'Dominican Republic', '', '214', 'DO', 'DOM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'es', 'DOP', '180'),
(61, 1, 'East Timor', '', '626', 'TP', 'TMP', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, '', 'USD', '670'),
(62, 1, 'Ecuador', '', '218', 'EC', 'ECU', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '([A-Z][0-9]{4}[A-Z]|(?:[A-Z]{2})?[0-9]{6})?', 0, 'es', 'ECS', '593'),
(63, 1, 'Egypt', '', '818', 'EG', 'EGY', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'ar', 'EGP', '20'),
(64, 1, 'El Salvador', '', '222', 'SV', 'SLV', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'es', 'SVC', '503'),
(65, 1, 'Equatorial Guinea', '', '226', 'GQ', 'GNQ', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'es', 'XAF', '240'),
(66, 1, 'Eritrea', '', '232', 'ER', 'ERI', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'aa', 'ERN', '291'),
(67, 1, 'Estonia', '', '233', 'EE', 'EST', '^(EE)?[0-9]{9}$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'et', 'EUR', '372'),
(68, 1, 'Ethiopia', '', '231', 'ET', 'ETH', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'am', 'ETB', '251'),
(69, 1, 'Falkland Islands (Malvinas)', '', '238', 'FK', 'FLK', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 'FIQQ 1ZZ', 0, 'en', 'FKP', '500'),
(70, 1, 'Faroe Islands', '', '234', 'FO', 'FRO', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{3}', 0, 'fo', 'DKK', '298'),
(71, 1, 'Fiji', '', '242', 'FJ', 'FJI', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'FJD', '679'),
(72, 1, 'Finland', '', '246', 'FI', 'FIN', '^(FI)?[0-9]{8}$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'fi', 'EUR', '358'),
(73, 1, 'France', '', '250', 'FR', 'FRA', '^(FR)?[0-9A-Z]{2}[0-9]{9}$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{2}[ ]?[0-9]{3}', 0, 'fr', 'EUR', '33'),
(75, 1, 'French Guiana', '', '254', 'GF', 'GUF', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '9[78]3[0-9]{2}', 0, 'fr', 'EUR', '594'),
(76, 1, 'French Polynesia', '', '258', 'PF', 'PYF', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '987[0-9]{2}', 0, 'fr', 'XPF', '689'),
(77, 1, 'French Southern Territories', '', '260', 'TF', 'ATF', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fr', 'EUR', '262'),
(78, 1, 'Gabon', '', '266', 'GA', 'GAB', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fr', 'XAF', '241'),
(79, 1, 'Gambia', '', '270', 'GM', 'GMB', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'GMD', '220'),
(80, 1, 'Georgia', '', '268', 'GE', 'GEO', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'ka', 'GEL', '995'),
(81, 1, 'Germany', '', '276', 'DE', 'DEU', '^(DE)?[0-9]{9}$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'de', 'EUR', '49'),
(82, 1, 'Ghana', '', '288', 'GH', 'GHA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'GHS', '233'),
(83, 1, 'Gibraltar', '', '292', 'GI', 'GIB', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'GIP', '350'),
(84, 1, 'Greece', '', '300', 'GR', 'GRC', '^(EL|GR)?[0-9]{9}$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{3}[ ]?[0-9]{2}', 0, 'el', 'EUR', '30'),
(85, 1, 'Greenland', '', '304', 'GL', 'GRL', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '39[0-9]{2}', 0, 'kl', 'DKK', '299'),
(86, 1, 'Grenada', '', '308', 'GD', 'GRD', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'XCD', '147'),
(87, 1, 'Guadeloupe', '', '312', 'GP', 'GLP', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '9[78][01][0-9]{2}', 0, 'fr', 'EUR', '590'),
(88, 1, 'Guam', '', '316', 'GU', 'GUM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '969[123][0-9]([ \\-][0-9]{4})?', 0, 'en', 'USD', '167'),
(89, 1, 'Guatemala', '', '320', 'GT', 'GTM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'es', 'QTQ', '502'),
(90, 1, 'Guinea', '', '324', 'GN', 'GIN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{3}', 0, 'fr', 'GNF', '224'),
(91, 1, 'Guinea-bissau', '', '624', 'GW', 'GNB', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'pt', 'GWP', '245'),
(92, 1, 'Guyana', '', '328', 'GY', 'GUY', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'GYD', '592'),
(93, 1, 'Haiti', '', '332', 'HT', 'HTI', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'ht', 'HTG', '509'),
(94, 1, 'Heard and McDonald Islands', '', '334', 'HM', 'HMD', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, '', 'AUD', '0'),
(95, 1, 'Honduras', '', '340', 'HN', 'HND', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '(?:[0-9]{5})?', 0, 'es', 'HNL', '504'),
(96, 1, 'Hong Kong', '', '344', 'HK', 'HKG', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'zh', 'HKD', '852'),
(97, 1, 'Hungary', '', '348', 'HU', 'HUN', '^(HU)?[0-9]{8}$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'hu', 'HUF', '36'),
(98, 1, 'Iceland', '', '352', 'IS', 'ISL', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{3}', 0, 'is', 'ISK', '354'),
(99, 1, 'India', '', '356', 'IN', 'IND', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{6}', 0, 'en', 'INR', '91'),
(100, 1, 'Indonesia', '', '360', 'ID', 'IDN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'id', 'IDR', '62'),
(101, 1, 'Iran, Islamic Republic of', '', '364', 'IR', 'IRN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fa', 'IRR', '98'),
(102, 1, 'Iraq', '', '368', 'IQ', 'IRQ', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'ar', 'IQD', '964'),
(103, 1, 'Ireland', '', '372', 'IE', 'IRL', '^(IE)?[0-9]S[0-9]{5}L$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'EUR', '353'),
(104, 1, 'Israel', '', '376', 'IL', 'ISR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{7}', 0, 'he', 'ILS', '972'),
(105, 1, 'Italy', '', '380', 'IT', 'ITA', '^(IT)?[0-9]{11}$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'it', 'EUR', '39'),
(106, 1, 'Jamaica', '', '388', 'JM', 'JAM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'JMD', '187'),
(107, 1, 'Japan', '', '392', 'JP', 'JPN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{3}-[0-9]{4}', 0, 'ja', 'JPY', '81'),
(108, 1, 'Jordan', '', '400', 'JO', 'JOR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'ar', 'JOD', '962'),
(109, 1, 'Kazakhstan', '', '398', 'KZ', 'KAZ', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{6}', 0, 'kk', 'KZT', '7'),
(110, 1, 'Kenya', '', '404', 'KE', 'KEN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'en', 'KES', '254'),
(111, 1, 'Kiribati', '', '296', 'KI', 'KIR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'AUD', '686'),
(112, 1, 'North Korea', '', '408', 'KP', 'PRK', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'ko', 'KPW', '850'),
(113, 1, 'Korea, Republic of', '', '410', 'KR', 'KOR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{3}[\\-][0-9]{3}', 0, 'ko', 'KRW', '82'),
(114, 1, 'Kuwait', '', '414', 'KW', 'KWT', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'ar', 'KWD', '965'),
(115, 1, 'Kyrgyzstan', '', '417', 'KG', 'KGZ', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{6}', 0, 'ky', 'KGS', '996'),
(116, 1, 'Lao People\'s Democratic Republic', '', '418', 'LA', 'LAO', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'lo', 'LAK', '856'),
(117, 1, 'Latvia', '', '428', 'LV', 'LVA', '^(LV)?[0-9]{11}$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'lv', 'LVL', '371'),
(118, 1, 'Lebanon', '', '422', 'LB', 'LBN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '([0-9]{4}([ ]?[0-9]{4})?)?', 0, 'ar', 'LBP', '961'),
(119, 1, 'Lesotho', '', '426', 'LS', 'LSO', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{3}', 0, 'en', 'LSL', '266'),
(120, 1, 'Liberia', '', '430', 'LR', 'LBR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'en', 'LRD', '231'),
(121, 1, 'Libyan Arab Jamahiriya', '', '434', 'LY', 'LBY', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'ar', 'LYD', '218'),
(122, 1, 'Liechtenstein', '', '438', 'LI', 'LIE', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '(948[5-9])|(949[0-7])', 0, 'de', 'CHF', '423'),
(123, 1, 'Lithuania', '', '440', 'LT', 'LTU', '^(LT)?([0-9]{9}|[0-9]{12})$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'lt', 'EUR', '370'),
(124, 1, 'Luxembourg', '', '442', 'LU', 'LUX', '^(LU)?[0-9]{8}$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'lb', 'EUR', '352'),
(125, 1, 'Macau', '', '446', 'MO', 'MAC', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'zh', 'MOP', '853'),
(126, 1, 'North Macedonia', '', '807', 'MK', 'MKD', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'mk', 'MKD', '389'),
(127, 1, 'Madagascar', '', '450', 'MG', 'MDG', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{3}', 0, 'fr', 'MGF', '261'),
(128, 1, 'Malawi', '', '454', 'MW', 'MWI', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'ny', 'MWK', '265'),
(129, 1, 'Malaysia', '', '458', 'MY', 'MYS', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'ms', 'MYR', '60'),
(130, 1, 'Maldives', '', '462', 'MV', 'MDV', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'dv', 'MVR', '960'),
(131, 1, 'Mali', '', '466', 'ML', 'MLI', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fr', 'XOF', '223'),
(132, 1, 'Malta', '', '470', 'MT', 'MLT', '^(MT)?[0-9]{8}$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'mt', 'EUR', '356'),
(133, 1, 'Marshall Islands', '', '584', 'MH', 'MHL', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '969[67][0-9]([ \\-][0-9]{4})?', 0, 'mh', 'USD', '692'),
(134, 1, 'Martinique', '', '474', 'MQ', 'MTQ', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '9[78]2[0-9]{2}', 0, 'fr', 'EUR', '596'),
(135, 1, 'Mauritania', '', '478', 'MR', 'MRT', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'ar', 'MRO', '222'),
(136, 1, 'Mauritius', '', '480', 'MU', 'MUS', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '([0-9]{3}[A-Z]{2}[0-9]{3})?', 0, 'en', 'MUR', '230'),
(137, 1, 'Mayotte', '', '175', 'YT', 'MYT', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '976[0-9]{2}', 0, 'fr', 'EUR', '262'),
(138, 1, 'Mexico', '', '484', 'MX', 'MEX', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'es', 'MXN', '52'),
(139, 1, 'Micronesia, Federated States of', '', '583', 'FM', 'FSM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '(9694[1-4])([ \\-][0-9]{4})?', 0, 'en', 'USD', '691'),
(140, 1, 'Moldova, Republic of', '', '498', 'MD', 'MDA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'ro', 'MDL', '373'),
(141, 1, 'Monaco', '', '492', 'MC', 'MCO', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '980[0-9]{2}', 0, 'fr', 'EUR', '377'),
(142, 1, 'Mongolia', '', '496', 'MN', 'MNG', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{6}', 0, 'mn', 'MNT', '976'),
(143, 1, 'Montserrat', '', '500', 'MS', 'MSR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'XCD', '166'),
(144, 1, 'Morocco', '', '504', 'MA', 'MAR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'ar', 'MAD', '212'),
(145, 1, 'Mozambique', '', '508', 'MZ', 'MOZ', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'pt', 'MZN', '258'),
(146, 1, 'Myanmar', '', '104', 'MM', 'MMR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'my', 'MMK', '95'),
(147, 1, 'Namibia', '', '516', 'NA', 'NAM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'NAD', '264'),
(148, 1, 'Nauru', '', '520', 'NR', 'NRU', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'na', 'AUD', '674'),
(149, 1, 'Nepal', '', '524', 'NP', 'NPL', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'ne', 'NPR', '977'),
(150, 1, 'Netherlands', '', '528', 'NL', 'NLD', '^(NL)?[0-9]{9}B[0-9]{2}$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[1-9][0-9]{3} ?[a-zA-Z]{2}', 0, 'nl', 'EUR', '31'),
(151, 1, 'Netherlands Antilles', '', '530', 'AN', 'ANT', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'nl', 'ANG', '599'),
(152, 1, 'New Caledonia', '', '540', 'NC', 'NCL', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '988[0-9]{2}', 0, 'fr', 'XPF', '687'),
(153, 1, 'New Zealand', '', '554', 'NZ', 'NZL', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'en', 'NZD', '64'),
(154, 1, 'Nicaragua', '', '558', 'NI', 'NIC', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '(([0-9]{4}-)?[0-9]{3}-[0-9]{3}(-[0-9]{1})?)?', 0, 'es', 'NIO', '505'),
(155, 1, 'Niger', '', '562', 'NE', 'NER', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'fr', 'XOF', '227'),
(156, 1, 'Nigeria', '', '566', 'NG', 'NGA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '([0-9]{6})?', 0, 'en', 'NGN', '234'),
(157, 1, 'Niue', '', '570', 'NU', 'NIU', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'NZD', '683'),
(158, 1, 'Norfolk Island', '', '574', 'NF', 'NFK', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '2899', 0, 'en', 'AUD', '672'),
(159, 1, 'Northern Mariana Islands', '', '580', 'MP', 'MNP', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '9695[012]([ \\-][0-9]{4})?', 0, 'tl', 'USD', '167'),
(160, 1, 'Norway', '', '578', 'NO', 'NOR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'nb', 'NOK', '47'),
(161, 1, 'Oman', '', '512', 'OM', 'OMN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '(PC )?[0-9]{3}', 0, 'ar', 'OMR', '968'),
(162, 1, 'Pakistan', '', '586', 'PK', 'PAK', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'ur', 'PKR', '92'),
(163, 1, 'Palau', '', '585', 'PW', 'PLW', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '96940', 0, 'en', 'USD', '680'),
(164, 1, 'Panama', '', '591', 'PA', 'PAN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'es', 'PAB', '507'),
(165, 1, 'Papua New Guinea', '', '598', 'PG', 'PNG', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{3}', 0, 'en', 'PGK', '675'),
(166, 1, 'Paraguay', '', '600', 'PY', 'PRY', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'es', 'PYG', '595'),
(167, 1, 'Peru', '', '604', 'PE', 'PER', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'es', 'PEN', '51'),
(168, 1, 'Philippines', '', '608', 'PH', 'PHL', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'tl', 'PHP', '63'),
(169, 1, 'Pitcairn', '', '612', 'PN', 'PCN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 'PCRN 1ZZ', 0, 'en', 'NZD', '870'),
(170, 1, 'Poland', '', '616', 'PL', 'POL', '^(PL)?[0-9]{10}$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{2}-[0-9]{3}', 0, 'pl', 'PLN', '48'),
(171, 1, 'Portugal', '', '620', 'PT', 'PRT', '^(PT)?[0-9]{9}$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}([\\-][0-9]{3})?', 0, 'pt', 'EUR', '351'),
(172, 1, 'Puerto Rico', '', '630', 'PR', 'PRI', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '00[679][0-9]{2}([ \\-][0-9]{4})?', 0, 'en', 'USD', '1'),
(173, 1, 'Qatar', '', '634', 'QA', 'QAT', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'ar', 'QAR', '974'),
(174, 1, 'Reunion', '', '638', 'RE', 'REU', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '9[78]4[0-9]{2}', 0, 'fr', 'EUR', '262'),
(175, 1, 'Romania', '', '642', 'RO', 'ROM', '^(RO)?[0-9]{2,10}$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{6}', 0, 'ro', 'RON', '40'),
(176, 1, 'Russian Federation', '', '643', 'RU', 'RUS', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{6}', 0, 'ru', 'RUB', '7'),
(177, 1, 'Rwanda', '', '646', 'RW', 'RWA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'rw', 'RWF', '250'),
(178, 1, 'Saint Kitts and Nevis', '', '659', 'KN', 'KNA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'XCD', '186'),
(179, 1, 'Saint Lucia', '', '662', 'LC', 'LCA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'XCD', '175'),
(180, 1, 'Saint Vincent and the Grenadines', '', '670', 'VC', 'VCT', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'XCD', '178'),
(181, 1, 'Samoa', '', '882', 'WS', 'WSM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'sm', 'WST', '685'),
(182, 1, 'San Marino', '', '674', 'SM', 'SMR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '4789[0-9]', 0, 'it', 'EUR', '378'),
(183, 1, 'Sao Tome and Principe', '', '678', 'ST', 'STP', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'pt', 'STD', '239'),
(184, 1, 'Saudi Arabia', '', '682', 'SA', 'SAU', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'ar', 'SAR', '966'),
(185, 1, 'Senegal', '', '686', 'SN', 'SEN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'fr', 'XOF', '221'),
(186, 1, 'Seychelles', '', '690', 'SC', 'SYC', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'SCR', '248'),
(187, 1, 'Sierra Leone', '', '694', 'SL', 'SLE', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'SLL', '232'),
(188, 1, 'Singapore', '', '702', 'SG', 'SGP', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{6}', 0, 'en', 'SGD', '65'),
(189, 1, 'Slovak Republic', '', '703', 'SK', 'SVK', '^(SK)?[0-9]{10}$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{3}[ ]?[0-9]{2}', 0, 'sk', 'EUR', '421'),
(190, 1, 'Slovenia', '', '705', 'SI', 'SVN', '^(SI)?[0-9]{8}$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'sl', 'EUR', '386'),
(191, 1, 'Solomon Islands', '', '090', 'SB', 'SLB', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'SBD', '677'),
(192, 1, 'Somalia', '', '706', 'SO', 'SOM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'so', 'SOS', '252'),
(193, 1, 'South Africa', '', '710', 'ZA', 'ZAF', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'zu', 'ZAR', '27'),
(194, 1, 'South Georgia and South Sandwich Islands', '', '239', 'GS', 'SGS', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 'SIQQ 1ZZ', 0, 'en', 'GBP', '500'),
(195, 1, 'Spain', '', '724', 'ES', 'ESP', '^(ES)?[0-9A-Z][0-9]{7}[0-9A-Z]$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'es', 'EUR', '34'),
(196, 1, 'Sri Lanka', '', '144', 'LK', 'LKA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'si', 'LKR', '94'),
(197, 1, 'St. Helena', '', '654', 'SH', 'SHN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '(ASCN|STHL) 1ZZ', 0, 'en', 'SHP', '290'),
(198, 1, 'St. Pierre and Miquelon', '', '666', 'PM', 'SPM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '9[78]5[0-9]{2}', 0, 'fr', 'EUR', '508'),
(199, 1, 'Sudan', '', '729', 'SD', 'SDN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'ar', 'SDG', '249'),
(200, 1, 'Suriname', '', '740', 'SR', 'SUR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'nl', 'SRD', '597'),
(201, 1, 'Svalbard and Jan Mayen Islands', '', '744', 'SJ', 'SJM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'no', 'NOK', '47'),
(202, 1, 'Swaziland', '', '748', 'SZ', 'SWZ', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[HLMS][0-9]{3}', 0, 'en', 'SZL', '268'),
(203, 1, 'Sweden', '', '752', 'SE', 'SWE', '^(SE)?(16|19|20)?[0-9]{6}-?[0-9]{4}?(01)?$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{3}[ ]?[0-9]{2}', 0, 'sv', 'SEK', '46'),
(204, 1, 'Switzerland', '', '756', 'CH', 'CHE', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'de', 'CHF', '41'),
(205, 1, 'Syrian Arab Republic', '', '760', 'SY', 'SYR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'ar', 'SYP', '963'),
(206, 1, 'Taiwan', '', '158', 'TW', 'TWN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{3}([0-9]{2})?', 0, 'zh', 'TWD', '886'),
(207, 1, 'Tajikistan', '', '762', 'TJ', 'TJK', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{6}', 0, 'tg', 'TJS', '992'),
(208, 1, 'Tanzania, United Republic of', '', '834', 'TZ', 'TZA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'sw', 'TZS', '255'),
(209, 1, 'Thailand', '', '764', 'TH', 'THA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'th', 'THB', '66'),
(210, 1, 'Togo', '', '768', 'TG', 'TGO', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fr', 'XOF', '228'),
(211, 1, 'Tokelau', '', '772', 'TK', 'TKL', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'NZD', '690'),
(212, 1, 'Tonga', '', '776', 'TO', 'TON', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'to', 'TOP', '676'),
(213, 1, 'Trinidad and Tobago', '', '780', 'TT', 'TTO', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'TTD', '186'),
(214, 1, 'Tunisia', '', '788', 'TN', 'TUN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'ar', 'TND', '216'),
(215, 1, 'Türkiye', '', '792', 'TR', 'TUR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'tr', 'TRY', '90'),
(216, 1, 'Turkmenistan', '', '795', 'TM', 'TKM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{6}', 0, 'tk', 'TMT', '993'),
(217, 1, 'Turks and Caicos Islands', '', '796', 'TC', 'TCA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 'TKCA 1ZZ', 0, 'en', 'USD', '164'),
(218, 1, 'Tuvalu', '', '798', 'TV', 'TUV', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'AUD', '688'),
(219, 1, 'Uganda', '', '800', 'UG', 'UGA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'UGX', '256'),
(220, 1, 'Ukraine', '', '804', 'UA', 'UKR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'uk', 'UAH', '380'),
(221, 1, 'United Arab Emirates', '', '784', 'AE', 'ARE', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'ar', 'AED', '971'),
(222, 1, 'United Kingdom', '', '826', 'GB', 'GBR', '^(GB)?([0-9]{9}([0-9]{3})?|[A-Z]{2}[0-9]{3})$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[a-zA-Z]{1,2}[0-9][0-9a-zA-Z]? ?[0-9][a-zA-Z]{2}', 1, 'en', 'GBP', '44'),
(223, 1, 'United States', '', '840', 'US', 'USA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%city, %zone_code %postcode\r\n%country_name', '[0-9]{5}([ \\-][0-9]{4})?', 0, 'en', 'USD', '1'),
(224, 1, 'United States Minor Outlying Islands', '', '581', 'UM', 'UMI', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'USD', '1'),
(225, 1, 'Uruguay', '', '858', 'UY', 'URY', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'es', 'UYU', '598'),
(226, 1, 'Uzbekistan', '', '860', 'UZ', 'UZB', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{6}', 0, 'uz', 'UZS', '998'),
(227, 1, 'Vanuatu', '', '548', 'VU', 'VUT', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'bi', 'VUV', '678'),
(228, 1, 'Vatican City State (Holy See)', '', '336', 'VA', 'VAT', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '00120', 0, 'la', 'EUR', '39'),
(229, 1, 'Venezuela', '', '862', 'VE', 'VEN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'es', 'VEF', '58'),
(230, 1, 'Viet Nam', '', '704', 'VN', 'VNM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'vi', 'VND', '84'),
(231, 1, 'Virgin Islands (British)', '', '092', 'VG', 'VGB', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'USD', '128'),
(232, 1, 'Virgin Islands (U.S.)', '', '850', 'VI', 'VIR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '008(([0-4][0-9])|(5[01]))([ \\-][0-9]{4})?', 0, 'en', 'USD', '134'),
(233, 1, 'Wallis and Futuna Islands', '', '876', 'WF', 'WLF', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '986[0-9]{2}', 0, 'fr', 'XPF', '681'),
(234, 1, 'Western Sahara', '', '732', 'EH', 'ESH', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'ar', 'MAD', '212'),
(235, 1, 'Yemen', '', '887', 'YE', 'YEM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'ar', 'YER', '967'),
(236, 1, 'Serbia', '', '381', 'RS', 'SRB', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'sr', 'RSD', '381'),
(237, 1, 'Democratic Republic of Congo', '', '180', 'CD', 'COD', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fr', 'XAF', '243'),
(238, 1, 'Zambia', '', '894', 'ZM', 'ZMB', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{5}', 0, 'en', 'ZMW', '260'),
(239, 1, 'Zimbabwe', '', '716', 'ZW', 'ZWE', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'ZWD', '263'),
(240, 1, 'Guernsey', '', '831', 'GG', 'GGY', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', '', '44'),
(241, 1, 'Montenegro', '', '499', 'ME', 'MNE', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', '', '382'),
(242, 1, 'Jersey', '', '832', 'JE', 'JEY', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', '', '44'),
(243, 1, 'Isle of Man', '', '833', 'IM', 'IMN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', '', '44'),
(244, 1, 'Åland Islands', '', '248', 'AX', 'ALA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'sv', 'EUR', '358');
-- -----
INSERT INTO `lc_languages` (`status`, `code`, `code2`, `name`, `locale`, `url_type`, `raw_date`, `raw_time`, `raw_datetime`, `format_date`, `format_time`, `format_datetime`, `decimal_point`, `thousands_sep`, `priority`) VALUES
(1, 'en', 'eng', 'English', 'en_US.utf8,en_US.UTF-8,english', 'none', 'm/d/y', 'h:i:s A', 'm/d/y h:i:s A', '%b %e %Y', '%I:%M %p', '%b %e %Y %I:%M %p', '.', ',', 0);
-- -----
INSERT INTO `lc_modules` (`id`, `module_id`, `type`, `status`, `priority`, `settings`, `last_log`) VALUES
(4, 'job_error_reporter', 'job', 1, 0, '{"status":"1","report_frequency":"Weekly","email_receipient":"","priority":"0"}', ''),
(5, 'job_cache_cleaner', 'job', 1, 0, '{"status":"1","priority":"0"}', '');
-- -----
INSERT INTO `lc_settings_groups` (`key`, `name`, `description`, `priority`) VALUES
('site_info', 'Site Info', 'Site information', 10),
('defaults', 'Defaults', 'Default settings', 20),
('social_media', 'Social Media', 'Settings related to social media.', 30),
('email', 'Email', 'Email and SMTP', 40),
('listings', 'Listings', 'Settings for the catalog listing', 50),
('legal', 'Legal', 'Legal settings and information', 70),
('images', 'Images', 'Settings for graphical elements', 80),
('advanced', 'Advanced', 'Advanced settings', 100);
-- -----
INSERT INTO `lc_settings` (`group_key`, `type`, `title`, `description`, `key`, `value`, `datatype`, `function`, `required`, `priority`) VALUES
('', 'global', 'Platform Database Version', 'The platform version of the database', 'platform_database_version', '1.0.0', 'string', '', 0, 0),
('site_info', 'global', 'Site Name', 'The name of your site.', 'site_name', '', 'string', 'text()', 1, 10),
('site_info', 'global', 'Site Email', 'The site\'s email address.', 'site_email', '', 'string', 'email()', 1, 11),
('site_info', 'global', 'Site Phone', 'The site\'s phone number.', 'site_phone', '', 'string', 'phone()', 1, 11),
('site_info', 'global', 'Site Time Zone', 'The site\'s time zone.', 'site_timezone', '', 'string', 'timezone()', 1, 19),
('site_info', 'local', 'Site Language', 'The spoken language of your organization.', 'site_language_code', 'en', 'string', 'language()', 1, 20),
('site_info', 'local', 'Site Country', 'The country of your organization.', 'site_country_code', 'US', 'string', 'country()', 1, 21),
('defaults', 'global', 'Default Language', 'The default language, if not identified.', 'default_language_code', 'en', 'string', 'language()', 1, 10),
('email', 'local', 'Send Emails', 'Whether or not the platform should deliver outgoing emails.', 'email_status', '1', 'boolean', 'toggle("y/n")', 0, 1),
('email', 'local', 'SMTP Enabled', 'Whether or not to use an SMTP server for delivering email.', 'smtp_status', '0', 'boolean', 'toggle("e/d")', 0, 10),
('email', 'local', 'SMTP Host', 'SMTP hostname, e.g. smtp.myprovider.com.', 'smtp_host', 'localhost', 'string', 'text()', 0, 11),
('email', 'local', 'SMTP Port', 'SMTP port, e.g. 25, 465 (SSL/TLS), or 587 (STARTTLS).', 'smtp_port', '25', 'number', 'number()', 0, 12),
('email', 'local', 'SMTP Username', 'Username for SMTP authentication.', 'smtp_username', '', 'string', 'text()', 0, 13),
('email', 'local', 'SMTP Password', 'Password for SMTP authentication.', 'smtp_password', '', 'string', 'password()', 0, 14),
('listings', 'global', 'Maintenance Mode', 'Maintenance mode will enable a slash screen that the site is down for maintenance.', 'maintenance_mode', '0', 'boolean', 'toggle("e/d")', 0, 2),
('listings', 'global', 'Important Notice', 'An important notice to be displayed above your website.', 'important_notice', '', 'boolean', 'regional_text()', 1, 0),
('listings', 'local', 'Items Per Page', 'The number of items to be displayed per page.', 'items_per_page', '20', 'number', 'number()', 0, 10),
('listings', 'local', 'Data Table Rows', 'The number of data table rows to be displayed per page.', 'data_table_rows_per_page', '25', 'number', 'text()', 0, 11),
('listings', 'local', 'Auto Decimals', 'Don\'t show decimals for integers. Will turn 99.00 into 99 but leave 99.99.', 'auto_decimals', '1', 'boolean', 'toggle("e/d")', 0, 21),
('legal', 'global', 'Cookie Policy', 'Select a page for the cookie policy or leave blank to disable.', 'cookie_policy', '', 'number', 'page()', 0, 10),
('legal', 'local', 'Privacy Policy', 'Select a page for the privacy policy consent or leave blank to disable.', 'privacy_policy', '', 'number', 'page()', 0, 11),
('images', 'global', 'Clear Thumbnails Cache', 'Remove all cached image thumbnails from disk.', 'cache_clear_thumbnails', '0', 'boolean', 'toggle()', 0, 1),
('images', 'local', 'Downsample', 'Downsample large uploaded images to best fit within the given dimensions of "width,height" or leave empty. Default: 2048,2048', 'image_downsample_size', '2048,2048', 'string', 'text()', 0, 34),
('images', 'local', 'Image Quality', 'The JPEG quality for uploaded images (0-100). Default: 90', 'image_quality', '90', 'number', 'number()', 0, 40),
('images', 'local', 'Thumbnail Quality', 'The JPEG quality for thumbnail images (0-100). Default: 65', 'image_thumbnail_quality', '65', 'number', 'number()', 0, 41),
('images', 'local', 'Interlaced Thumbnails', 'Generate interlaced thumbnail images for progressive loading. Increases the filesize by 10-20% but improves user experience.', 'image_thumbnail_interlaced', '0', 'boolean', 'toggle()', 0, 42),
('images', 'local', 'Whitespace Color', 'Set the color of any generated whitespace to the given RGB value. Default: 255,255,255', 'image_whitespace_color', '255,255,255', 'string', 'text()', 0, 43),
('images', 'local', 'AVIF Enabled', 'Use AVIF images if supported by the browser.', 'avif_enabled', '0', 'boolean', 'toggle("e/d")', 0, 44),
('images', 'local', 'WebP Enabled', 'Use WebP images if supported by the browser.', 'webp_enabled', '0', 'boolean', 'toggle("e/d")', 0, 45),
('advanced', 'global', 'GZIP Enabled', 'Compresses browser data. Increases the load on the server but decreases the bandwidth.', 'gzip_enabled', '1', 'boolean', 'toggle("e/d")', 5, 0),
('advanced', 'global', 'System Cache Enabled', 'Enables the system cache module which caches frequently used data.', 'cache_enabled', '1', 'boolean', 'toggle("e/d")', 0, 10),
('advanced', 'global', 'Clear System Cache', 'Remove all cached system information.', 'cache_clear', '0', 'boolean', 'toggle("y/n")', 0, 11),
('advanced', 'global', 'Static Content Domain Name', 'Use the given alias domain name for static content (images, stylesheets, javascripts) e.g. https://static.domain.tld/', 'static_domain', '', 'string', 'url()', 0, 12),
('advanced', 'local', 'Control Panel Link', 'The URL to your control panel, e.g. cPanel.', 'control_panel_link', 'https://', 'string', 'url()', 0, 18),
('advanced', 'local', 'Database Admin Link', 'The URL to your database manager, e.g. phpMyAdmin.', 'database_admin_link', 'https://', 'string', 'url()', 0, 19),
('advanced', 'local', 'Webmail Link', 'The URL to your webmail client.', 'webmail_link', 'https://', 'string', 'url()', 0, 20),
('security', 'local', 'CAPTCHA', 'Prevent robots from posting form data by enabling CAPTCHA security.', 'captcha_enabled', '1', 'boolean', 'toggle("e/d")', 0, 16),
('social_media', 'global', 'Facebook Link', 'The link to your Facebook page.', 'facebook_link', '#', 'string', 'url()', 0, 10),
('social_media', 'global', 'Instagram Link', 'The link to your Instagram page.', 'instagram_link', '#', 'string', 'url()', 0, 20),
('social_media', 'global', 'LinkedIn Link', 'The link to your LinkedIn page.', 'linkedin_link', '#', 'string', 'url()', 0, 30),
('social_media', 'global', 'Pinterest Link', 'The link to your Pinterest page.', 'pinterest_link', '#', 'string', 'url()', 0, 40),
('social_media', 'global', 'Twitter Link', 'The link to your Twitter page.', 'twitter_link', '#', 'string', 'url()', 0, 50),
('social_media', 'global', 'YouTube Link', 'The link to your YouTube channel.', 'youtube_link', '#', 'string', 'url()', 0, 60),
('', 'global', 'Template', '', 'template', 'default', 'string', 'template()', 1, 0),
('', 'global', 'Template Settings', '', 'template_settings', '{"sidebar_parallax_effect":"1","compact_category_tree":"0","cookie_acceptance":"1"}', 'string', 'text()', 0, 0),
('', 'global', 'Jobs Last Run', 'Time when background jobs were last ran.', 'jobs_last_run', NOW(), 'string', 'text()', 0, 0),
('', 'global', 'Jobs Last Push', 'Time when background jobs were last pushed for execution.', 'jobs_last_push', NOW(), 'string', 'text()', 0, 0);
